### ISSUE TITLE
Any plans for AUR pkg ?

### ISSUE THREAD

**Issue by DarkXero-dev** [HimDek/Utterly-Nord-Plasma#9] opened 2023-04-05 15:08 UTC
As title says .. I dunno how to make PKGBUILDs was hoping it would be published to AUR for us Arch users, instead of having to manually get each set n put in right location ?

Just an idea..

**Comment by xythrez** [comment] 2023-09-18 06:16
Based on the response from #2 , I've went ahead and created the packages [utterly-round-plasma-style](https://aur.archlinux.org/packages/utterly-round-plasma-style) and [utterly-nord-plasma](https://aur.archlinux.org/packages/utterly-nord-plasma)

**Comment by HimDek** [comment] 2024-05-05 00:48
Duplicate of #2

**Closed by HimDek** 2024-05-05 00:48 UTC
Labels: duplicate
